name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore Pacman _V2.sln
      
    - name: Build
      run: dotnet build Pacman _V2.sln --no-restore -c Release
      
    - name: Test
      run: dotnet test Pacman _V2.sln --no-build --verbosity normal
      
    - name: Docker Build
      run: docker build -t Pacman _V2 .
